definitions: 
  steps:
    - step: &deploy
        script:
          - export DOCKER_COMPOSE_VERSION=1.18.0
          - export DOCKER_COMPOSE_URL=https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)
          - curl -L $DOCKER_COMPOSE_URL > docker-compose
          - chmod +x docker-compose
          - mv docker-compose /usr/local/bin
          - echo ${DOCKERHUB_PASSWORD} | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
          - docker-compose pull kestrel
          - docker-compose build nginx
          - docker-compose -f docker-compose.yml up -d
pipelines:
  branches:
    master:
      - step:
          name: Build and Push Docker Hub
          deployment: Production
          script:
            - echo ${DOCKERHUB_PASSWORD} | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
            - IMAGE=huseyinorer/netcore
            - docker build -f MainProject/Dockerfile -t ${IMAGE}:latest .
            - docker push "${IMAGE}:latest"
          services:
            - docker
      - step:
          <<: *deploy
          name: Deploy to ubuntu
         

