pipelines:
  branches:
    master:
      - step:
          name: Build and Push Docker Hub
          deployment: Production
          script:
            - >-
              echo ${DOCKERHUB_PASSWORD} | docker login --username
              "$DOCKERHUB_USERNAME" --password-stdin
            - IMAGE=huseyinorer/netcore
            - 'docker build -f MainProject/Dockerfile -t ${IMAGE}:latest .'
            - 'docker push "${IMAGE}:latest"'
          services:
            - docker
      - step:
            image: huseyinorer/netcore:latest
            script:
             - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
             - docker-compose -f docker-compose.yml pull
             - docker-compose -f docker-compose.yml up -d
            name: deploy
            deployment: deploy
         

