version: "3.7"

services:
    nginx:
        build: ./nginx
        links:
           - kestrel:kestrel
        ports:
            - "80:80"
        restart: always
        
    kestrel:
        build: .
        ports:
            - "5000"
        restart: always
    
      
