// <auto-generated />
using System;
using MainProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace MainProject.Migrations.ProjectDb
{
    [DbContext(typeof(ProjectDbContext))]
    [Migration("20200810115436_ProjectDb")]
    partial class ProjectDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("MainProject.Models.HomeSliderPhotos", b =>
                {
                    b.Property<int>("PhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("bytea");

                    b.Property<DateTime>("PhotoAddDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PhotoTitle")
                        .HasColumnType("text");

                    b.HasKey("PhotoId");

                    b.ToTable("HomeSliderPhotos");
                });

            modelBuilder.Entity("MainProject.Models.Settings", b =>
                {
                    b.Property<string>("WebSiteName")
                        .HasColumnType("text");

                    b.Property<string>("Credentials_Email")
                        .HasColumnType("text");

                    b.Property<string>("Credentials_Password")
                        .HasColumnType("text");

                    b.HasKey("WebSiteName");

                    b.ToTable("Settings");
                });
#pragma warning restore 612, 618
        }
    }
}
