name: Docker Image CI
on: push
jobs:
  build-container:
    name: container image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag huseyinorer/netcoregit
    - name: publish hub
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: huseyinorer/netcoregit
        tags: latest
