name: Docker Image CI
on: push
jobs:
  build-container:
    name: container image
    runs-on: ubuntu-latest
    steps:    
    - name: Build the Docker image
      uses: actions/checkout@v2   
    - name: publish hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: huseyinorer/netcoregit
        tags: latest
        dockerfile: ./MainProject/Dockerfile
    - name: Executing remote  command
      uses: appleboy/ssh-action@master
      with:
        USERNAME: vmserver
        host: ${{ secrets.HOST }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: whoami
