name: Docker Image CI
on: push
jobs:
  build-container:
    name: container image
    runs-on: ubuntu-latest
    steps:    
    - name: Build the Docker image
      uses: actions/checkout@v2   
    - name: publish hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: huseyinorer/netcoregit
        tags: latest
        dockerfile: ./MainProject/Dockerfile
    - name: Executing remote  command
      uses: JimCronqvist/action-ssh@master
      with:
        hosts: 'vmserver@34.66.179.159'
        privateKey: ${{ secrets.SSHKEY }}
        command:  |
         docker-compose -f docker-compose.yml pull
         docker-compose -f docker-compose.yml up -d
